### ISSUE TITLE
开源了个压缩包...

### ISSUE THREAD

**Issue by xun404** [work7z/CodeGen#1]
希望可以真正开源或者功能插件化.....一个人的力量总是有限的。

**Comment by work7z** [comment]
Hi xun404

我很能理解您的关切，但很抱歉目前暂无开源计划，主要是在开源之前，一般都需要写好注释、文档、开发规范等等步骤，而这过程往往花费的时间可能会很久，同时这个项目还涉及多个本地服务的运行，可能暂不便进行开源。

目前本仓库是希望通过issue区来收集用户反馈的意见和bug，如果后期实在开发不过来了，或者长期不维护了(三个月为上限的停更)，则一定会开源并整理相关流程的的。

另外关于功能插件化，CodeGen也会往这方向努力进展，比如提供本地命令行调用，用户自定义插件开发等等，作为开发者我也会继续努力开发的。

Best Regards
CodeGen ToolBox

**Comment by work7z** [comment]
您好，本工具箱已开源v2.0.0所有代码，欢迎审查与关注，链接为https://github.com/work7z/LafTools
