### ISSUE TITLE
m1 文件损坏

### ISSUE THREAD

**Issue by lxm278693** [work7z/CodeGen#10]
m1 文件损坏

**Comment by work7z** [comment]
抱歉哈，这个是因为CodeGen还没有买年付证书，您可以在安全性设置点击信任。

不过CodeGen也在调整为web版和插件版本中

Sent from my iPhone

On Apr 25, 2022, at 23:38, lxm278693 ***@***.***> wrote:

﻿

m1 文件损坏

**Comment by work7z** [comment]
您好，1.3.0已经发布，这个问题应该解决了，麻烦您在官网下载重新试一下哈
