### ISSUE TITLE
LInux APPImage版本白屏

### ISSUE THREAD

**Issue by xmu714** [work7z/CodeGen#11]
静态服务器新建完成以后，点击启动后就白屏了，编辑的时候也会白屏，需要按Ctrl+R刷新，但是刷新就回到了主页，无法看见服务器编辑页面

**Comment by work7z** [comment]
感谢反馈哈，我这边调试一下，去尝试复现一下。这个有可能是因为服务器端口冲突了，最近CodeGen再重新整理，会再测试一下的

Sent from my iPhone

On Apr 27, 2022, at 09:20, xmu714 ***@***.***> wrote:

﻿

静态服务器新建完成以后，点击启动后就白屏了，编辑的时候也会白屏，需要按Ctrl+R刷新，但是刷新就回到了主页，无法看见服务器编辑页面

**Comment by work7z** [comment]
您好，1.3.0已经发布，这个问题应该解决了，麻烦您在官网下载重新试一下哈
