### ISSUE TITLE
服务端代码呢？

### ISSUE THREAD

**Issue by RagueI** [work7z/CodeGen#14]

**Comment by work7z** [comment]
目前已经开源了客户端代码，因为涉及到一些代码漏洞和缺陷的审查，以及一些开发文档的工作也还在进行，所以其他代码还在整理中，敬请理解哈

**Comment by work7z** [comment]
您好，本工具箱已开源v2.0.0所有代码，欢迎审查与关注，链接为https://github.com/work7z/LafTools
