### ISSUE TITLE
更新问题

### ISSUE THREAD

**Issue by Zi-long** [work7z/CodeGen#15]
更新失败
![image](https://user-images.githubusercontent.com/68323881/171367869-e8954223-d3cc-4089-9dfb-b9f35d5c7b39.png)

**Comment by work7z** [comment]
您好，请问目前使用的版本是什么呢？如果是1.2.x的旧版本，可能要麻烦您在官网重新下载完整的安装包

**Comment by work7z** [comment]
或者您也可以在官网联系方式找到QQ群号，加入QQ群，我这边一起看起来，很抱歉带来不便

**Comment by Zi-long** [comment]
QQ群在哪里？我的问题是在软件内选择更新会出
![image](https://user-images.githubusercontent.com/68323881/171811592-c6119015-b3fb-43ad-8383-d65bc97b9879.png)

**Comment by work7z** [comment]
您好，QQ群是106038310，欢迎您加入然后这边也看一下。

如果您暂时不需要更新的话，也可以点击”下次提醒“那个按钮。最主要的问题，如果您的版本低于1.3.0，可能是需要重新进行安装的

**Comment by Zi-long** [comment]
好的，谢谢

**Comment by work7z** [comment]
不客气的哈

如果是1.2.x的旧版本，的确是会404的，因为版本有较大迭代，1.3.0后需要重新安装
