### ISSUE TITLE
win11下生成了错误的backend文件夹路径

### ISSUE THREAD

**Issue by william4094** [work7z/CodeGen#17]
您好，
我的安装路径是：
D:\Program Files\codegen-v1.4.5-windows-x64
点击startup.bat后，创建了以下目录：
D:\Program%20Files\codegen-v1.4.5-windows-x64\codegen-toolbox-v1.4.5-windows-x64\procedures\v1.4.5\backend
请确认程序是否有路径空格处理问题

**Comment by work7z** [comment]
您好，好的我这里会检查关于空格问题的处理，感谢您的反馈，之前测试这一块应该是可以的….我这边再检查一下

**Comment by work7z** [comment]
您好，我检查了应该是不影响功能使用，但的确是有这个空格的问题，谢谢您的反馈，我们正在着手进行修复，有任何问题都会及时反馈的

**Comment by work7z** [comment]
您好，这个问题已经解决了，如果还有出现的情况请随时联系哈，很抱歉有这个问题
