### ISSUE TITLE
数据库管理无法链接

### ISSUE THREAD

**Issue by 1307super** [work7z/CodeGen#19]
版本: 1.6.13
问题: 无论是连本地库,还是线上的测试库, 都返回: 通信链路故障 最后一个成功发送到服务器的数据包是0毫秒前。驱动程序尚未收到来自服务器的任何数据包。

**Comment by work7z** [comment]
您好，您用的是MySQL数据库对吗？我们这边测试一下，稍等哈，另外方便的话麻烦提供一下数据库版本号.....

**Comment by 1307super** [comment]
嗯嗯 是的 mysql, 版本号: 5.7.36

**Comment by work7z** [comment]
好的哈，那我这边试试5.7的版本，理论上应该是兼容的

**Comment by work7z** [comment]
<img width="1342" alt="image" src="https://user-images.githubusercontent.com/60811462/188785401-d0af654f-1a0b-4932-b928-7d80391cf01e.png">

@1307super 这里测试mysql应该是可以连接的。根据错误信息，可能是网络链路问题，可能需要您看一下网络配置.....  不确定是不是5.7版本兼容问题，我这边也安装5.7版本试试

**Comment by 1307super** [comment]
嗯嗯 好的哈, 主要是我在项目里,或者Navicat都能正常连上, 在codegen里就提示这个, 我换个低版本的mysql试试看

**Comment by work7z** [comment]
嗯嗯，好的。这个估计也和驱动版本有关系.... 我再检查一下，实在抱歉

**Comment by 1307super** [comment]
嗯嗯 我试了一下5.6 没问题, 5.7.26也正常, 不过5.7.30及以上就不正常了, 26-30之间目前没测试

**Comment by work7z** [comment]
不客气的哈，这是我们应该做的事情。  

理论上当前数据库，应该只会包含当前数据库的表，我们是通过JDBC驱动的官方driver API查询的。 不过我们也会再关注这个问题，检查是否属于bug，谢谢您的理解 :P

**Comment by work7z** [comment]
另外，如已升级1.6.51版本，也请升级到1.6.52，因为有一些页面渲染问题1.6.51需要被修复
