### ISSUE TITLE
为什么不能自定义安装路径？

### ISSUE THREAD

**Issue by D-Ayden** [work7z/CodeGen#2]
如题，不想安装在C盘，可以自定义安装路径吗？

**Comment by work7z** [comment]
您好

实在抱歉哈，因为目前主要注重在功能开发，还没有对安装流程和目录进行配置，后续几个版本会进行这方面的改进的。

计划在接下来几个版本里推出绿色版，可能是暂时的解决方案，敬请关注

Best Regards
CodeGen ToolBox

**Comment by D-Ayden** [comment]
> 您好
> 
> 实在抱歉哈，因为目前主要注重在功能开发，还没有对安装流程和目录进行配置，后续几个版本会进行这方面的改进的。
> 
> 计划在接下来几个版本里推出绿色版，可能是暂时的解决方案，敬请关注
> 
> Best Regards CodeGen ToolBox

好的，十分感谢

**Comment by work7z** [comment]
@D-Ayden  Hi Ayden. 感谢关注，目前CodeGen已支持自定义目录安装了，可以重新下载安装包试一下(注意目录尽量不要选择带空格或者中文的路径哈，否则可能会报错)
