### ISSUE TITLE
AES加密工具报错

### ISSUE THREAD

**Issue by Handy045** [work7z/CodeGen#21]
使用软件更新，从1.5.93更新之1.6.32版本后：

新的AES加密点击生成秘钥报错：
```
Error: /opt/app/codegen-toolbox/extensions/encryption_and_decryption_codegen_api_v1.6.2/encryption_and_decryption/pre-requisite.json (No such file or directory)
```

请问该如何修复中间版本的资源缺失？

**Comment by Handy045** [comment]
对了，我使用的是docker版本

**Comment by work7z** [comment]
您好，这个错误应该是下载依赖时网络中断导致不太完整..... 或者您可以试试在依赖库里找到encryption_and_decryption，重新安装试一下..... 

我这边也正在复查，初步检查了传统安装包以及在线版本是可以的，docker版本还在检查中，或者您可以先使用在线版本试试哈。


<img width="1071" alt="image" src="https://user-images.githubusercontent.com/60811462/189705510-a8ffb911-b006-4368-816b-1af3bd3bb5c4.png">

**Comment by Handy045** [comment]
okok 谢谢啦

**Comment by work7z** [comment]
不客气哈，如果还是无法解决这个问题，可以加我们QQ群106038310
