### ISSUE TITLE
多行文本格式化为一行的工具？Multiple lines of text formatted into a single line？

### ISSUE THREAD

**Issue by willxiang** [work7z/CodeGen#22]
示例（example）：
12345564564,
154265411,
154265411

格式化后（formated）：
12345564564,154265411,154265411

是否能增加一款这样的小工具吗？
类似功能未能在工具箱中找到，谢谢！

Could one of these gadgets be added? Similar features cannot be found in the toolbox， Thanks !

**Comment by work7z** [comment]
您好，可以的哈，这类小工具很实用！我们这边会加入的，十分感谢您的建议。  

Sure, we will develop and release these features in the following version of the toolbox asap, please kindly stay tuned, thanks!

**Comment by work7z** [comment]
您好，v1.6.61已经发布此功能，您可以在文本工具里找到此功能。  

Hi, we have released the line conversion tool since version v1.6.61, you can find it in Text Tools.
