### ISSUE TITLE
希望能提供一个下划线、中划线和驼峰互转的功能。

### ISSUE THREAD

**Issue by quanjw** [work7z/CodeGen#25]
我新接手的项目中接口是驼峰的，但是转换成接口就变成中划线了，在根据接口找代码的时候太麻烦了。
Thanks~

**Comment by work7z** [comment]
好的，感谢您的建议！我们这几个版本就会加入这个功能，敬请期待哈

**Comment by work7z** [comment]
您好，v1.6.61已经发布此功能，可以进行目标格式转换，转为下划线、中划线、驼峰等格式。  

如果有更多建议，或者此功能不符合预期，麻烦您再open这个issue哈，谢谢建议
