### ISSUE TITLE
CDN静态资源安装报错

### ISSUE THREAD

**Issue by tk914** [work7z/CodeGen#27]
版本1.7.12
从1.6.81更新到1.7.12后，尝试使用CND静态资源功能，在下载完依赖后就出现下面报错
![image](https://user-images.githubusercontent.com/76687240/194864562-e089b2d3-e856-4bd6-b52b-80b62431e374.png)

使用离线安装后一直显示这个页面
![image](https://user-images.githubusercontent.com/76687240/194865438-3a4790f6-1172-4069-a545-77ebd4080435.png)

**Comment by work7z** [comment]
您好，很抱歉产生这个错误，您是在线安装还是离线安装呢？   方便进一步QQ群沟通，我们排查一下问题吗

QQ Group: 106038310

**Comment by work7z** [comment]
这边网络不太通畅，看不到您的图片.... 近期可能国内通讯工具会更加方便
