### ISSUE TITLE
搜索功能异常

### ISSUE THREAD

**Issue by woniuxia** [work7z/CodeGen#29]
如下图，搜索 转义没有结果
![image](https://user-images.githubusercontent.com/16383685/207518129-75374e4b-6128-4a3a-b42a-21192de00dca.png)
![image](https://user-images.githubusercontent.com/16383685/207518149-999e2aba-65e8-4e16-ae19-8a7c90a4ffb4.png)

**Comment by work7z** [comment]
抱歉，这个当时是以具体功能名进行检索的... 所以可能没有检索到菜单栏的匹配，我们会进行优化的，谢谢反馈哈
