### ISSUE TITLE
加载失败

### ISSUE THREAD

**Issue by zjr-g** [work7z/CodeGen#3]
![image](https://user-images.githubusercontent.com/60166043/162579751-89602671-a21b-4a23-b6e1-e74816215889.png)

**Comment by zjr-g** [comment]
> ![image](https://user-images.githubusercontent.com/60166043/162579751-89602671-a21b-4a23-b6e1-e74816215889.png)

版本是官网下的v1.2.2稳定版

**Comment by work7z** [comment]
Hi zjr-g

很抱歉，我这边检查一下，方便说一下你使用的平台吗

**Comment by zjr-g** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年4月9日(星期六) 晚上11:20
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [work7z/CodeGen] 加载失败 (Issue #3)





 
Hi zjr-g
 
很抱歉，我这边检查一下，方便说一下你使用的平台吗

**Comment by zjr-g** [comment]
> Hi zjr-g
> 
> 很抱歉，我这边检查一下，方便说一下你使用的平台吗

windows的平台
![image](https://user-images.githubusercontent.com/60166043/162580492-41b0489f-70eb-4e86-936d-e5dd84905705.png)

**Comment by work7z** [comment]
我这边测试好像不会出现这个情况..... 方便进群沟通吗？106038310

**Comment by work7z** [comment]
或者你可以先试试把用户主目录的.codegen目录删除，然后重新启动试一下，有可能是它在启动时被意外停止，导致文件不完整

**Comment by zjr-g** [comment]
> 我这边测试好像不会出现这个情况..... 方便进群沟通吗？106038310

已申请入群，好的我试试

**Comment by work7z** [comment]
嗯嗯

**Comment by work7z** [comment]
fixed
