### ISSUE TITLE
文本差异工具

### ISSUE THREAD

**Issue by woniuxia** [work7z/CodeGen#31]
文本差异工具无法通过鼠标滚轮进行滚动

**Comment by work7z** [comment]
您好，我们已经发现这个情况，这个应该属于feature，但我们后续也会继续不断改进的。

默认的多页面模式是不会通过鼠标滚轮滚动，如果需要可以点击菜单栏上侧的山形按钮，如下图哈

<img width="950" alt="image" src="https://user-images.githubusercontent.com/60811462/208234039-5f2efba6-ac16-4f3d-bf94-bbb3dde6b050.png">
