### ISSUE TITLE
翻译问题

### ISSUE THREAD

**Issue by a869375583** [work7z/CodeGen#32]
翻译的好像都出错 翻译不了

**Comment by work7z** [comment]
您好，能否提供具体翻译错误信息呢？我们这边测试好像是可以的
<img width="684" alt="image" src="https://user-images.githubusercontent.com/60811462/212100531-2ed01107-fbe3-49f7-a215-5c4c5170d97f.png">

您是指这个翻译功能吗
https://cloud.codegen.cc/trans/trans_text

**Comment by a869375583** [comment]
![image](https://user-images.githubusercontent.com/42175593/212100868-bc20129c-d128-43b1-88cb-0a1f2fba3d02.png)

**Comment by a869375583** [comment]
好像是你们限制了账户的最大翻译词数

**Comment by a869375583** [comment]
"sorry, it seems that your account has reached the maximum translation service(50k words).  To control the overheads of CodeGen, we would like to disallow your translation service temporarily, You can translate the texts in the next month. In addition, If you want to use this service right now please contact us via mailbox at work7z@outlook.com"

**Comment by work7z** [comment]
对的，这个是为了避免用户翻译数量过多，不过我们刚刚已经取消了这个限制，您重新试一下，看看可以吗

**Comment by a869375583** [comment]
可以了 谢谢

**Comment by a869375583** [comment]
+
