### ISSUE TITLE
下载前验证码 一直提示 验证码不正确，请重试或刷新代码。试了很多次都不成功

### ISSUE THREAD

**Issue by evrins** [work7z/CodeGen#36]
系统版本 macOS Sonoma 14.2
浏览器版本 Chrome 120.0.6099.129

复现步骤:
1. 打开网址 http://codegen.cc/v2/nav/verify-download?type=prod&version=v1.8.65&name=codegen-v1.8.65-arm64.tar.gz
2. 输入图像验证码
3. 点击 “验证您的操作” 按钮
4. 然后网页提示 “验证码不正确，请重试或刷新代码。“

一个疑惑的点:
每次在 “图像验证码” 输入都会触发请求 getDownloadLinkByVCode 带着当前输入的验证码, 点击 “验证您的操作” 没有发送请求.

**Comment by work7z** [comment]
很抱歉，我们正在检查中

Sent from my iPhone

On Jan 5, 2024, at 20:51, Evrins Hu ***@***.***> wrote:

﻿

系统版本 macOS Sonoma 14.2
浏览器版本 Chrome 120.0.6099.129

复现步骤:

  1.  打开网址 http://codegen.cc/v2/nav/verify-download?type=prod&version=v1.8.65&name=codegen-v1.8.65-arm64.tar.gz
  2.  输入图像验证码
  3.  点击 “验证您的操作” 按钮
  4.  然后网页提示 “验证码不正确，请重试或刷新代码。“

一个疑惑的点:
每次在 “图像验证码” 输入都会触发请求 getDownloadLinkByVCode 带着当前输入的验证码, 点击 “验证您的操作” 没有发送请求.

**Comment by work7z** [comment]
您好，

现在这个问题已经复现并修复完毕，如果还存在此问题烦请再次反馈哈。

非常抱歉，这是一个低级的错误，我们预期用户输入正确密码的时候动态发送请求，但是没在Button点击事件进行处理，这段逻辑已经被补充上去。

如果后续使用过程中还有其他问题，欢迎随时提出，感谢

**Comment by evrins** [comment]
验证通过
已修复

**Comment by work7z** [comment]
感谢回复，将关闭此单
