### ISSUE TITLE
win11上显示白屏

### ISSUE THREAD

**Issue by SCzfdf** [work7z/CodeGen#5]
![图片](https://user-images.githubusercontent.com/30040164/163712317-822c99e6-21cf-4324-9174-667c4584e7a5.png)

**Comment by SCzfdf** [comment]
从Website 下载的win 1.2.8版本

**Comment by work7z** [comment]
感谢反馈，我们这边测试一下哈，之前win11版本的确是会有空白情况，抱歉哈

**Comment by work7z** [comment]
如果有有解决这个问题，会及时向您反馈的

**Comment by work7z** [comment]
您好，刚刚检查了发现是依赖问题，已经重新打包并发布了，麻烦您在官网重新下载哈，感谢关注

**Comment by SCzfdf** [comment]
> 您好，刚刚检查了发现是依赖问题，已经重新打包并发布了，麻烦您在官网重新下载哈，感谢关注

不行,并且新版本会报毒...
![image](https://user-images.githubusercontent.com/30040164/163716222-042f7518-6524-464a-a577-3e9caab5b6ad.png)

这是新版本的文件大小, 不知道是不是下载了正确的安装包
![image](https://user-images.githubusercontent.com/30040164/163716432-b8dbece7-94b9-4056-98b2-ce81e0137b90.png)

**Comment by work7z** [comment]
对的，这个是新版本的大小。

报毒这个是因为没买代码签名.... 这个安全证书估计除了360还要买苹果、微软的， 因为目前Beta版本主攻功能，所以还没弄这一块，但是可以放心CodeGen没有任何病毒的，请点击信任然后执行即可

如果还是不行的话，麻烦您把用户主目录的.codegen删除，然后原来的程序卸载掉再试试。如果还是不行的话，可能麻烦您进群提供一些更详细的信息
