### ISSUE TITLE
官网下载也太拉了把，越往后越慢，这是用的百度云吗

### ISSUE THREAD

**Issue by 2219160052** [work7z/CodeGen#6]

**Comment by work7z** [comment]
很抱歉，官网下载用的国内付费CDN服务，需要一些时间预热才能提高下载效率，所以刚开始下载会有一些慢，正常应该是满速的

刚刚已经把部署程序重新修改了一下，目前是会提前进行URL预热，这个情况应该不会存在了，如果还有的话麻烦帮忙反馈一下哈，谢谢

**Comment by 2219160052** [comment]
ok，好了
