### ISSUE TITLE
ubuntu 20 登录后白屏  java python 页面不登录白屏

### ISSUE THREAD

**Issue by liuliu36** [work7z/CodeGen#7]

**Comment by work7z** [comment]
您好，很抱歉带来这个问题，我们正在重新整理代码，在重构CodeGen逻辑，计划将其作为插件的形式，在VSCode和Jetbrains里支持，可能除了安装应用也会以插件方式安装，会更轻量更方便，白屏的问题我们也会尽快排查的

感谢您的关注与支持

**Comment by work7z** [comment]
您好，1.3.0已经发布，这个问题应该解决了，麻烦您在官网下载重新试一下哈
