### ISSUE TITLE
mac pro M1提示文件已损坏

### ISSUE THREAD

**Issue by liuliu36** [work7z/CodeGen#8]

**Comment by work7z** [comment]
您好，这个是因为CodeGen暂时未购买年付证书的原因，如果可以的话麻烦您在安全性设置进行配置，信任CodeGen以运行。

另外，我们近期正在重构CodeGen逻辑，将其作为插件的形式，在VSCode和Jetbrains里支持，可能除了安装应用也会以插件方式安装，会更轻量更方便
